"use client";

import { useEffect, useMemo, useState } from "react";

import { getBasketProductConfig, priorityLabels, quantityLabel } from "../lib/basket-config";
import { availableYears, basketCostByYear, compareBasket, type BasketItem, type ComparisonRow } from "../lib/calculations";
import { loadGroceryDataset } from "../lib/data";
import type { GroceryDataset, ProductPriority } from "../types/grocery";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const whole = new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 });
type ReceiptMode = "starting" | "comparison" | "budget-fit";

function Receipt({ year, rows, budget, mode }: { year: number; rows: ComparisonRow[]; budget: number; mode: ReceiptMode }) {
  const starting = mode === "starting";
  const visibleRows = mode === "budget-fit" ? rows.filter((row) => row.adjustedQuantity > 0) : rows;
  const total = visibleRows.reduce((sum, row) => sum + (starting ? row.baseCost : row.currentPrice * (mode === "budget-fit" ? row.adjustedQuantity : row.quantity)), 0);
  const copy = mode === "starting" ? ["Starting-year basket", "Selected basket before comparison"] : mode === "comparison" ? ["Comparison-year basket", "Selected basket before adjustments"] : ["Budget-fit basket", "Priority-aware simulation"];
  return <section className={`receipt receipt-${mode}`} aria-label={`${copy[0]} for ${year}`}><div className="receipt-heading"><div><span>{year} U.S. city average</span><strong>{copy[0]}</strong></div><small>{copy[1]}</small></div><div className="receipt-rule" /><div className="receipt-list">{visibleRows.map((row) => { const quantity = mode === "budget-fit" ? row.adjustedQuantity : row.quantity; const price = starting ? row.basePrice : row.currentPrice; const cost = starting ? row.baseCost : price * quantity; const detail = mode === "budget-fit" && row.adjustment === "reduced" ? `Reduced from ${quantityLabel(row.quantity, row.unit)}` : `${quantityLabel(quantity, row.unit)} at ${money.format(price)} ${getBasketProductConfig(row).priceBasis}`; return <div className="receipt-row" key={row.id}><span><strong>{row.name}</strong><small>{detail}</small></span><strong>{money.format(cost)}</strong></div>; })}</div><div className="receipt-rule" /><div className="receipt-total"><span>{mode === "budget-fit" ? "Final simulated total" : "Selected basket total"}</span><strong>{money.format(total)}</strong></div>{mode !== "starting" && <div className={`receipt-balance${budget - total < 0 ? " negative" : ""}`}><span>{budget - total < 0 ? "Over selected budget" : "Left in budget"}</span><strong>{money.format(Math.abs(budget - total))}</strong></div>}</section>;
}

function TrendChart({ points }: { points: { year: number; cost: number }[] }) {
  const width = 700; const height = 240; const pad = 34; const max = Math.max(...points.map((point) => point.cost)); const min = Math.min(...points.map((point) => point.cost)); const scaleX = (index: number) => pad + (index / Math.max(points.length - 1, 1)) * (width - pad * 2); const scaleY = (value: number) => height - pad - ((value - min) / Math.max(max - min, 1)) * (height - pad * 2); const line = points.map((point, index) => `${index ? "L" : "M"}${scaleX(index)},${scaleY(point.cost)}`).join(" ");
  return <svg className="trend-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Basket cost over selected years"><title>Basket cost over time</title><line x1={pad} x2={width - pad} y1={height - pad} y2={height - pad} className="chart-grid" /><path d={line} className="chart-line" />{points.map((point, index) => <g key={point.year}><circle cx={scaleX(index)} cy={scaleY(point.cost)} r="4" className="chart-point"><title>{`${point.year}: ${money.format(point.cost)}`}</title></circle>{(index === 0 || index === points.length - 1 || index % 3 === 0) && <text x={scaleX(index)} y={height - 10} textAnchor="middle">{point.year}</text>}</g>)}</svg>;
}

function ContributionChart({ rows }: { rows: ComparisonRow[] }) { const max = Math.max(...rows.map((row) => row.contribution), 1); return <div className="contribution-chart" role="img" aria-label="Largest contributors to the basket increase">{rows.map((row) => <div className="contribution-row" key={row.id}><div className="contribution-label"><span>{row.name}</span><strong>{money.format(row.contribution)}</strong></div><div className="contribution-track"><div className="contribution-bar" style={{ width: `${Math.max(0, row.contribution / max) * 100}%` }} /></div></div>)}</div>; }

export function GroceryBasketApp() {
  const [dataset, setDataset] = useState<GroceryDataset | null>(null); const [error, setError] = useState<string | null>(null); const [basket, setBasket] = useState<BasketItem[]>([]); const [baseYear, setBaseYear] = useState<number | null>(null); const [comparisonYear, setComparisonYear] = useState<number | null>(null); const [budget, setBudget] = useState(30); const [dark, setDark] = useState(false);
  useEffect(() => { loadGroceryDataset().then((data) => { setDataset(data); setBasket(data.products.map((product) => ({ ...product, included: true, quantity: product.defaultQuantity, priority: "prefer-to-keep" }))); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "The grocery price data could not be loaded.")); }, []);
  const years = useMemo(() => dataset ? availableYears(dataset, basket) : [], [dataset, basket]);
  useEffect(() => { if (!years.length) return; if (!baseYear || !years.includes(baseYear)) setBaseYear(years[0]); const valid = years.filter((year) => year > (baseYear ?? years[0])); if (!comparisonYear || !valid.includes(comparisonYear)) setComparisonYear(valid.includes(2024) ? 2024 : valid.at(-1) ?? null); }, [years, baseYear, comparisonYear]);
  const result = useMemo(() => dataset && baseYear && comparisonYear ? compareBasket(dataset, basket, baseYear, comparisonYear, budget) : null, [dataset, basket, baseYear, comparisonYear, budget]); const trend = useMemo(() => dataset ? basketCostByYear(dataset, basket, years) : [], [dataset, basket, years]);
  if (error) return <main className="app-shell"><p className="status error">{error}</p></main>; if (!dataset || !result || !baseYear || !comparisonYear) return <main className="app-shell"><p className="status">Loading grocery price data...</p></main>;
  const updateItem = (id: string, update: Partial<Pick<BasketItem, "included" | "quantity" | "priority">>) => setBasket((items) => items.map((item) => item.id === id ? { ...item, ...update } : item));
  const selected = basket.filter((item) => item.included && item.quantity > 0); const comparisonOptions = years.filter((year) => year > baseYear); const increase = result.currentTotal - result.baseTotal; const percentChange = result.baseTotal ? increase / result.baseTotal * 100 : 0; const reduced = result.rows.filter((row) => row.adjustment === "reduced"); const removed = result.rows.filter((row) => row.adjustment === "removed"); const protectedRows = result.rows.filter((row) => row.priority === "must-keep"); const adjustments = reduced.length + removed.length; const topItem = result.rows[0]; const startYear = years[0]; const endYear = years.at(-1); const fullFits = result.budgetDifference >= 0; const budgetFitsAfterSimulation = result.adjustedBudgetDifference >= 0;
  return <main className={`app-shell ${dark ? "theme-dark" : "theme-light"}`}>
    <header className="hero"><div><p className="eyebrow">Grocery price comparison</p><h1>The Shrinking Grocery Basket</h1><p>Compare the same grocery basket across time and see how far your budget still goes.</p></div><label className="theme-switch"><input type="checkbox" checked={dark} onChange={(event) => setDark(event.target.checked)} /><span>Dark mode</span></label></header>
    <section className="section scenario opening-section" aria-labelledby="comparison-heading"><p className="section-kicker">1. Set the comparison</p><h2 id="comparison-heading">Choose years and budget</h2><p className="section-copy">Set the years first, then review what the selected basket costs before any budget adjustment.</p><div className="year-availability"><strong>Available comparison range: {startYear} to {endYear}</strong><span>{whole.format(years.length)} complete years are available for all {whole.format(selected.length)} selected items. Changing the basket can change this range; a year that is no longer valid resets to an available year.</span></div><div className="scenario-controls"><label>Starting year<select value={baseYear} onChange={(event) => setBaseYear(Number(event.target.value))}>{years.slice(0, -1).map((year) => <option value={year} key={year}>{year}</option>)}</select></label><label>Comparison year<select value={comparisonYear} onChange={(event) => setComparisonYear(Number(event.target.value))}>{comparisonOptions.map((year) => <option value={year} key={year}>{year}</option>)}</select></label><label>Grocery budget<input type="number" min="1" max="200" step="5" value={budget} onChange={(event) => setBudget(Number(event.target.value) || 0)} /></label></div><p className="budget-context">A {money.format(budget)} grocery budget {fullFits ? `covers the selected comparison-year basket and leaves ${money.format(result.budgetDifference)} remaining.` : `does not cover the full comparison-year basket; it is ${money.format(Math.abs(result.budgetDifference))} over budget.`}</p></section>
    <section className="section basket-section" aria-labelledby="basket-heading"><div className="section-heading"><div><p className="section-kicker">2. Basket and priorities</p><h2 id="basket-heading">Basket used in this comparison</h2><p className="section-copy">Set a priority for each item. Flexible items are adjusted first; Must keep items are never adjusted automatically.</p></div><p className="selection-count"><strong>{whole.format(selected.length)}</strong> items selected</p></div><div className="basket-editor" aria-label="Basket item controls">{basket.map((item) => { const config = getBasketProductConfig(item); return <article className={`basket-item priority-${item.priority}${item.included && item.quantity > 0 ? "" : " is-excluded"}`} key={item.id}><label className="include-control"><input type="checkbox" checked={item.included} onChange={(event) => updateItem(item.id, { included: event.target.checked })} /><span className="sr-only">Include {item.name}</span></label><div className="basket-item-name"><strong>{item.name}</strong><small>{quantityLabel(item.quantity, item.unit)} in basket; price {config.priceBasis}</small><em>{config.approximateEquivalent ? `About: ${config.approximateEquivalent}` : ""}</em></div><label className="priority-control">Priority<select value={item.priority} onChange={(event) => updateItem(item.id, { priority: event.target.value as ProductPriority })}>{Object.entries(priorityLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><div className="quantity-control"><button type="button" aria-label={`Decrease ${item.name} quantity`} disabled={item.quantity <= 0} onClick={() => updateItem(item.id, { quantity: Math.max(0, item.quantity - 1) })}>-</button><label><span className="sr-only">Quantity for {item.name}</span><input type="number" min="0" max="20" step="1" value={item.quantity} onChange={(event) => updateItem(item.id, { quantity: Number(event.target.value) || 0 })} /></label><button type="button" aria-label={`Increase ${item.name} quantity`} disabled={item.quantity >= 20} onClick={() => updateItem(item.id, { quantity: Math.min(20, item.quantity + 1) })}>+</button></div></article>; })}</div></section>
    <section className="section basket-glance" aria-labelledby="glance-heading"><p className="section-kicker">3. Basket at a glance</p><h2 id="glance-heading">What is in the basket</h2><p className="section-copy">The same fixed quantities are compared across both selected years.</p><div className="glance-grid">{selected.map((item) => { const config = getBasketProductConfig(item); return <article key={item.id}><strong>{item.name}</strong><span>{quantityLabel(item.quantity, item.unit)}</span><small>{config.priceBasis}{config.approximateEquivalent ? `; ${config.approximateEquivalent}` : ""}</small></article>; })}</div></section>
    <section className="section receipt-comparison-section" aria-labelledby="basket-cost-heading"><p className="section-kicker">4. Basket cost</p><h2 id="basket-cost-heading">What the same basket costs in {comparisonYear}</h2><p className="section-copy">These are the selected items before the priority-aware simulation changes anything.</p><div className="receipts receipt-comparison"><Receipt year={baseYear} rows={result.rows} budget={budget} mode="starting" /><Receipt year={comparisonYear} rows={result.rows} budget={budget} mode="comparison" /></div><div className="comparison-bridge"><span>Starting-year basket</span><strong>{money.format(result.baseTotal)}</strong><b>to</b><span>Comparison-year basket</span><strong>{money.format(result.currentTotal)}</strong><em>{increase >= 0 ? "+" : ""}{money.format(increase)} ({percentChange.toFixed(1)}%)</em></div></section>
    <section className="section budget-section" aria-labelledby="budget-heading"><p className="section-kicker">5. Budget fit</p><h2 id="budget-heading">What still fits within your {money.format(budget)} budget</h2><p className="section-copy">Flexible items are reduced first, then removed if needed. Prefer to keep items are adjusted only when flexible changes are insufficient. Must keep items stay unchanged.</p><div className="budget-layout"><Receipt year={comparisonYear} rows={result.rows} budget={budget} mode="budget-fit" /><div className={`receipt-summary${budgetFitsAfterSimulation ? " is-within" : ""}`}><div><span>Comparison-year basket</span><strong>{money.format(result.currentTotal)}</strong></div><div><span>Selected budget</span><strong>{money.format(budget)}</strong></div><div><span>Protected items</span><strong>{whole.format(protectedRows.length)}</strong></div><div><span>Items reduced</span><strong>{whole.format(reduced.length)}</strong></div><div><span>Items removed</span><strong>{whole.format(removed.length)}</strong></div><div><span>Final simulated total</span><strong>{money.format(result.remainingTotal)}</strong></div><div><span>Amount remaining</span><strong>{money.format(Math.max(0, result.adjustedBudgetDifference))}</strong></div><div><span>{result.protectedShortfall ? "Unresolved shortfall" : "Savings from adjustments"}</span><strong>{money.format(result.protectedShortfall || result.currentTotal - result.remainingTotal)}</strong></div></div></div>{result.protectedShortfall > 0 ? <p className="budget-context">Your Must keep items leave a {money.format(result.protectedShortfall)} shortfall. Adjust priorities, increase the budget, or review basket quantities.</p> : <p className="budget-context">{adjustments ? `${whole.format(adjustments)} item adjustments were made. Must keep items remained unchanged.` : "No adjustments were needed for this budget."}</p>}</section>
    <section className="section evidence" aria-labelledby="evidence-heading"><p className="section-kicker">6. Evidence</p><h2 id="evidence-heading">What changed the most</h2><div className="charts"><article><h3>Basket cost over time</h3><TrendChart points={trend} /><p className="helper">Only years with complete annual prices for every selected item are shown.</p></article><article><h3>Largest dollar contributors</h3><ContributionChart rows={result.rows.slice(0, 6)} /><p className="helper">Dollar contribution to the basket change from {baseYear} to {comparisonYear}.</p></article></div></section>
    <section className="section findings" aria-labelledby="findings-heading"><p className="section-kicker">7. Key findings</p><h2 id="findings-heading">The comparison at a glance</h2><p className="findings-lede">The selected basket costs {money.format(increase)} more in {comparisonYear} than in {baseYear}.</p><div className="key-stats" aria-label="Key comparison values"><div><span>Starting-year basket</span><strong>{money.format(result.baseTotal)}</strong></div><div><span>Comparison-year basket</span><strong>{money.format(result.currentTotal)}</strong></div><div><span>Dollar change</span><strong>{increase >= 0 ? "+" : ""}{money.format(increase)}</strong></div><div><span>Price change</span><strong>{percentChange.toFixed(1)}%</strong></div></div><div className="findings-grid"><article><strong>{topItem.name} has the largest dollar increase</strong><span>Its price change adds {money.format(topItem.contribution)} to the full basket.</span></article><article><strong>{whole.format(protectedRows.length)} item{protectedRows.length === 1 ? " is" : "s are"} protected</strong><span>{reduced.length} items were reduced and {removed.length} were removed by the selected priorities.</span></article><article><strong>{result.protectedShortfall ? "The budget cannot cover protected items" : "The priority-aware basket fits the budget"}</strong><span>{result.protectedShortfall ? `${money.format(result.protectedShortfall)} remains above budget after all eligible changes.` : `The final simulated total is ${money.format(result.remainingTotal)}, leaving ${money.format(result.adjustedBudgetDifference)}.`}</span></article></div></section>
    <details className="methodology"><summary>Methodology and limitations</summary><div className="methodology-content"><section><h3>Data source</h3><p>Annual item prices are based on U.S. city-average grocery price series and aggregated into annual averages. See the <a href="https://www.bls.gov/cpi/factsheets/average-prices.htm" target="_blank" rel="noreferrer">BLS Average Price Data</a> and <a href="https://fred.stlouisfed.org/" target="_blank" rel="noreferrer">FRED data sources</a>.</p></section><section><h3>Price calculation</h3><p>Each annual item price is multiplied by the selected quantity. The selected basket total is the sum of those item totals for the chosen year.</p></section><section><h3>Priority-aware budget simulation</h3><p>Priorities are chosen by the visitor. Flexible items are reduced in configured whole-unit steps, then removed if needed. Prefer to keep items are adjusted only if flexible changes are insufficient. Must keep items are not changed automatically. Within a priority level, the largest cost reduction is applied first.</p></section><section><h3>Missing data and limitations</h3><ul><li>Years without complete prices for every selected item are excluded rather than estimated.</li><li>Priorities are subjective and do not represent nutritional needs or household preferences.</li><li>Product units differ by item, and annual averages do not capture sales, substitutions, taxes, or local price variation.</li><li>This is a budget simulation, not nutritional or shopping advice.</li></ul></section></div></details>
  </main>;
}
